language: node_js
node_js: 12
before_deploy: npm run predeploy
deploy:
    provider: firebase
    token:
        secure: PzE6eNOi8GWQ3ZE/WIW6S1kzuJ8Pd9jQx4f9AX56RlpLHYlVmkaiv7/BnWRmMs00cNCuCr7eS1xhfpFgR8Cz1tKatIv4i1T55IjJqW74QEdMo4XKQeHj7oJtsBle3cBPubfWCzuiWRGr9POqg65d/O+dxSihQUCXYGdLNizWiJy5+ZpzJ/BCCwlVnpjNVTWMs6A/MNzdgY6xaSOFIu+I7VKxJHs9AguMYg1HbvOyiFFp72S+tg8MbZ7PKBSM9q1Zm+5lF1Wcm8pXcvFfroMFN3v3uOEB/zD1+SYUTvrbuKcQwOGKqUHh15mNpEkfJDQDNMEMC0Z6aJH2P/wSjxVhwJNQuWIzHKJMpO7Y1Tizgm3wdkPercpIFjA5Y9uBuZgeltsQgNV9UOKHOs5rgjG8Kz1DWpBeoOTGBft4vsMBaPwcQ1bo+H7Sm89FHrpaDfGcm5J4tUKrI2lnY8AIJH4j37V4cL34RCWLcJauY0IlctdR6D/LZ9wTed7iUtUPdIDZQRzC0DtqjMFeGs7a6pwe2oicUqdOOqdUkYGdl4Tz/zInjC8g26nMhvseSTCEa/DXSN3IZ7KSVdRf+zh9Kz9t3juN4A9lKL2Xeb/iNpLSNMnmtQv7cl5RYXVckM1sSUWtu3+sgN1jsuJnMCvLX7fwLGZUNxmWPX8l7tMU0QJg2M0=
