language: node_js
node_js: 12
before_deploy: npm run predeploy
deploy:
    provider: firebase
    token:
        secure: VOcWz5sLICtwj+HOLP9UW3tLQCik6Xo+ups42t0+PxxP1t4DeQuUoNUCoEcgdDwQkqb3zpe0D+9l/FtAaetLab07m/Bo2HtvcxpKC1zLjkC+6B2uH34XD/vLaBznyWqAvG5XiMkTAvAvt1XioYYNJaqgNaD9UK5AI488rystQDRCrD4K++QaKvoWgIFWUUCdKBiqLcSXkJ06/CVG8eDdrzB6lo4tpjr8ONIgT/ozrSyxsxMEQ1Ehjw2Pap6tDl8dUKBtu+SCJ4EcXg549pGPDpxsjIYF46JEFAFZpQWtC8lBpgo3Yoy5mY2V9MX88cire0HCBsWkror1TxrHqHV5o/aaMe31395fa+O07Al9TOuPNLSqlXD4SfrfqYv2yQt9MhhCsp2PdupvdqxaahnwOVBWjZSPXeCQ8sGSml3jTT9AjYpxMmlD6aRvPjSYraJBxz8n3wRjz7RjFmHKzVTR/uiMAWNU98D1xbguAvQDKa1etJqQsO6UdPmtekOFvFYogWr0zZgozOnfyR1dMCRNbKSAFqHOyShDAIUnyEbuPhuPGiIFS1aHsco7gOIV9VlLV15lPQqLDz54R1dKo1O5d0c59T/t/vZKnrZ6WlJntnBMUldfg1F0sDyX29r5LeGQCrzRNZwiG/mn9CsyDU0cvKbMK4+T+bw1An2kqt+eMFA=
